# Site settings
title: qichen zhang
email: hello@qichenzhang.com
description: > # this means to ignore newlines until "baseurl:"
  Crass + SASS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qichenzhang.com" # the base hostname & protocol for your site
twitter_username: wiscotheque
github_username:  qichenz
keybase_key:  80D7 46E0 3374 4A11

# Build settings
markdown: kramdown

# Pagination
paginate: 3
paginate_path: "/blog/page/:num/"

#Gems
gems: ["jemoji"]

category_archive path: ""
